version: '3.8'
services:
  terkdestiny-frontend:
    build: .
    container_name: trekdestiny_frontend
    volumes:
      - ./src:/app/src
    ports:
      - 8080:80
    restart: on-failure
    networks:
      - trekdestiny-frontend

networks:
  trekdestiny-frontend:
