version: '3.8'
services:
  terkdestiny-frontend:
    build: .
    container_name: trekdestiny_frontend
    volumes:
      - /etc/letsencrypt/ssl/trekdestiny_certificate.pem:/etc/nginx/ssl/trekdestiny_cetrificate.pem
      - /etc/letsencrypt/ssl/trekdestiny_key.pem:/etc/nginx/ssl/trekdestiny_key.pem
    ports:
      - 443:443
    restart: on-failure
    networks:
      - trekdestiny-frontend

networks:
  trekdestiny-frontend:
